$axure.loadCurrentPage({
  "url":"档案页面.html",
  "generationDate":new Date(1431854790667.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b6e22f7ffcf345339f6dfd8dced02b85",
    "type":"Axure:Page",
    "name":"档案页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd66a095628947168110c314d2ad2144",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":182,
              "y":-8},
            "size":{
              "width":450,
              "height":731}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5106d928069c42c09ad2509fc8bc3c1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":182,
                  "y":-8},
                "size":{
                  "width":450,
                  "height":731}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u0.png"}},
{
          "id":"4332b73d466940d9b668816ac64dcaf3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":247,
              "y":112},
            "size":{
              "width":320,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3966764486d74ac89263a2fc1b1634a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":247,
                  "y":112},
                "size":{
                  "width":320,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u15.png"}},
{
          "id":"115653c5addd4ed0b5fb26d72f2c5dc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":421,
              "y":114},
            "size":{
              "width":21,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd9ab91b30534824bde2d90e32e6add7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":421,
                  "y":114},
                "size":{
                  "width":21,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u17.png"}},
{
          "id":"3a8f0d3af9c94760bcb4ea265915c501",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":446,
              "y":114},
            "size":{
              "width":22,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"186c2be479014cdf8c49ac806c3b5b3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":446,
                  "y":114},
                "size":{
                  "width":22,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u19.png"}},
{
          "id":"783135906867457990b4cbcdb0ed4f1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":471,
              "y":116},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eb11661dd244b4c83a311dd3196118f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":471,
                  "y":116},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆/u21.png"}},
{
          "id":"cf07acfb45014711b0eb87556de1b474",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Black Black', 'Arial Black'",
            "location":{
              "x":501,
              "y":114},
            "size":{
              "width":60,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40bdc49aeff74355957ab3a3906a7dbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Black Black', 'Arial Black'",
                "location":{
                  "x":501,
                  "y":114},
                "size":{
                  "width":60,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"085f88c484594b7284955c32449b97aa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":247,
              "y":138},
            "size":{
              "width":320,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd4860a30e4e05a5f7af521af251fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":247,
                  "y":138},
                "size":{
                  "width":320,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u12.png"}},
{
          "id":"49fc9008bc1b41b0b1f1b35583514fea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":138},
            "size":{
              "width":33,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52e3ee873fe547fab16652fec3701d87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":248,
                  "y":138},
                "size":{
                  "width":33,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 档案列表 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"档案列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案页面/u14.png"}},
{
          "id":"17c94861f4c34a099baa768ac7e757a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":530,
              "y":136},
            "size":{
              "width":37,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba05921e4f34ce5a0ec242bfa782816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":530,
                  "y":136},
                "size":{
                  "width":37,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle (Image)",
                      "objectsToFades":[{
                          "objectPath":["aac4a5e9993c497aaaecc9a612c38cba"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案页面/u16.png"}},
{
          "id":"0153fdcab9454f40a1d03b3604e0b959",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":248,
              "y":170},
            "size":{
              "width":319,
              "height":420}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move (Image) with drag y",
                      "objectsToMoves":[{
                          "objectPath":["85ef9c19cae0492ebef5e07369a50055"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ba8e12d9c68946adbd178f491fd71a0d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"85ef9c19cae0492ebef5e07369a50055",
                  "label":"",
                  "parentDynamicPanel":"0153fdcab9454f40a1d03b3604e0b959",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-4,
                      "y":0},
                    "size":{
                      "width":325,
                      "height":561}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6a163e6ba294fc58c7df719981a1bda",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0153fdcab9454f40a1d03b3604e0b959",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-4,
                          "y":0},
                        "size":{
                          "width":325,
                          "height":561}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/档案页面/u19.jpg"}}]}]},
{
          "id":"aac4a5e9993c497aaaecc9a612c38cba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":347,
              "y":170},
            "size":{
              "width":220,
              "height":110},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"342b037f418e4fb28794a15c1eaa4935",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":347,
                  "y":170},
                "size":{
                  "width":220,
                  "height":110},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案页面/u21.png"}},
{
          "id":"5a972e9f64634e489c74c2ee88c5d421",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":373,
              "y":144},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b4f6ebbcedb4398b583bca17ca7b994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":373,
                  "y":144},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fd66a095628947168110c314d2ad2144":{
      "scriptId":"u0"},
    "5106d928069c42c09ad2509fc8bc3c1b":{
      "scriptId":"u1"},
    "4332b73d466940d9b668816ac64dcaf3":{
      "scriptId":"u2"},
    "3966764486d74ac89263a2fc1b1634a6":{
      "scriptId":"u3"},
    "115653c5addd4ed0b5fb26d72f2c5dc1":{
      "scriptId":"u4"},
    "bd9ab91b30534824bde2d90e32e6add7":{
      "scriptId":"u5"},
    "3a8f0d3af9c94760bcb4ea265915c501":{
      "scriptId":"u6"},
    "186c2be479014cdf8c49ac806c3b5b3e":{
      "scriptId":"u7"},
    "783135906867457990b4cbcdb0ed4f1c":{
      "scriptId":"u8"},
    "4eb11661dd244b4c83a311dd3196118f":{
      "scriptId":"u9"},
    "cf07acfb45014711b0eb87556de1b474":{
      "scriptId":"u10"},
    "40bdc49aeff74355957ab3a3906a7dbb":{
      "scriptId":"u11"},
    "085f88c484594b7284955c32449b97aa":{
      "scriptId":"u12"},
    "f9dd4860a30e4e05a5f7af521af251fb":{
      "scriptId":"u13"},
    "49fc9008bc1b41b0b1f1b35583514fea":{
      "scriptId":"u14"},
    "52e3ee873fe547fab16652fec3701d87":{
      "scriptId":"u15"},
    "17c94861f4c34a099baa768ac7e757a5":{
      "scriptId":"u16"},
    "eba05921e4f34ce5a0ec242bfa782816":{
      "scriptId":"u17"},
    "0153fdcab9454f40a1d03b3604e0b959":{
      "scriptId":"u18"},
    "85ef9c19cae0492ebef5e07369a50055":{
      "scriptId":"u19"},
    "e6a163e6ba294fc58c7df719981a1bda":{
      "scriptId":"u20"},
    "aac4a5e9993c497aaaecc9a612c38cba":{
      "scriptId":"u21"},
    "342b037f418e4fb28794a15c1eaa4935":{
      "scriptId":"u22"},
    "5a972e9f64634e489c74c2ee88c5d421":{
      "scriptId":"u23"},
    "5b4f6ebbcedb4398b583bca17ca7b994":{
      "scriptId":"u24"}}});