$axure.loadCurrentPage({
  "url":"在线咨询.html",
  "generationDate":new Date(1431048594031.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"num"],
  "page":{
    "packageId":"c03df66091484552b42ee238a58026c1",
    "type":"Axure:Page",
    "name":"在线咨询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a51d40b3e0c14b66b84493e173887085",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":261,
              "y":80},
            "size":{
              "width":389,
              "height":803}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbd31caf67f04a16bc4a598ca3c01ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":261,
                  "y":80},
                "size":{
                  "width":389,
                  "height":803}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u0.png"}},
{
          "id":"276d522fac284b03a2f4719cf6b08be8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":299,
              "y":201},
            "size":{
              "width":313,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d7e84e74144ecd9e9989d4bae5763a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":299,
                  "y":201},
                "size":{
                  "width":313,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u17.png"}},
{
          "id":"c0ddd0e224ba476ba645f91598bbf739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":307,
              "y":212},
            "size":{
              "width":4,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7899fcf0b50641eca6574f49c8d46232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":307,
                  "y":212},
                "size":{
                  "width":4,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u19.png"}},
{
          "id":"17e0d1eaaa8a49a1b1024b6dedf3a162",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":313,
              "y":209},
            "size":{
              "width":4,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"263f645751964dd085ca48bb6064f700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":313,
                  "y":209},
                "size":{
                  "width":4,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u21.png"}},
{
          "id":"d208d3b62fc44835941a51cd306705aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":310,
              "y":211},
            "size":{
              "width":4,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d98559435b24b32b0d294c15c1575a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":310,
                  "y":211},
                "size":{
                  "width":4,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u23.png"}},
{
          "id":"6eaf96a41e7d4e2b958bc41001a783c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":320,
              "y":205},
            "size":{
              "width":4,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c05e1a766e0c49f7ad1c0e0fe0a3fb91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":320,
                  "y":205},
                "size":{
                  "width":4,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u25.png"}},
{
          "id":"fb266b05adc84507aa585b63e002f2a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":585,
              "y":205},
            "size":{
              "width":21,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56dae8b43d934593aef2e8efb59e3e3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":585,
                  "y":205},
                "size":{
                  "width":21,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u27.png"}},
{
          "id":"9a28271f901b49dbbd5420c9c6d76b11",
          "label":"iPhoneTime",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":432,
              "y":201},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efc1e169de384f0f93eacaaf27d2a9db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":432,
                  "y":201},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2ae8a4dc5cae47e1a855f15843d8d345",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"13px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":300,
              "y":220},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12421999c394477a95b6b95355baa39f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"13px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":300,
                  "y":220},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u31.png"}},
{
          "id":"8ed702da76e0437793c8f5865a455f44",
          "label":"BUTTON_BACK",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":304,
              "y":223},
            "size":{
              "width":29,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08d2d5378dd9428b8d7871b1376cb9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":304,
                  "y":223},
                "size":{
                  "width":29,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec4e9bf25a364eb6b785e533f43e53de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":304,
              "y":290},
            "size":{
              "width":309,
              "height":195}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"523a067fa7254b76b017ba0644c2e7d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":304,
                  "y":290},
                "size":{
                  "width":309,
                  "height":195}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线咨询/u20.png"}},
{
          "id":"187b62b8f5944dedbbc92630866610a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":293},
            "size":{
              "width":295,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35aca19ec5764ce9a279ba12b078b346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":293},
                "size":{
                  "width":295,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a46ebb3d74544f2b595c7476e721e4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":335},
            "size":{
              "width":295,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32fc2d7eeda248dc8613c5fba885053a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":335},
                "size":{
                  "width":295,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af3ab596bcfb4aa2887ffc63b7255ce5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":311,
              "y":377},
            "size":{
              "width":295,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d82d32118a7b40a0b2fb090760140668",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":311,
                  "y":377},
                "size":{
                  "width":295,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc0f8cba707f40cfa85b771af6e680da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":311,
              "y":419},
            "size":{
              "width":295,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073fffc698c048e9be11852e0f612236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":311,
                  "y":419},
                "size":{
                  "width":295,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"536e66b28bd74cbfa73c3d5cbf5371c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":314,
              "y":495},
            "size":{
              "width":299,
              "height":220}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c4cfb46de564f01b00c55360a9e5875",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":314,
                  "y":495},
                "size":{
                  "width":299,
                  "height":220}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/在线咨询/u30.png"}},
{
          "id":"6559d4ea74164ee5bd28ec86114742eb",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":324,
              "y":580},
            "size":{
              "width":276,
              "height":62}},
          "adaptiveStyles":{
}},
{
          "id":"730e900946bb41d28fe0ee92e2c658bd",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":390,
              "y":670},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"198817a2fb7540a1bdbf797164051e26",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":650,
              "y":354},
            "size":{
              "width":200,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fd8752a18cb4429965d654ce686a3d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":650,
                  "y":354},
                "size":{
                  "width":200,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b64a8d1261dc49b9998757e4cfcb40ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":510},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"013f6fbb2dcd45cbad51ef9f3ebdae98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":510},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c09d6a5a5fa49038d53bd1913b0f725",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":396.5,
              "y":510},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"47756d43436c413ca39f44e11158dd66",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":329,
              "y":554},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cccf88834044edeb670a8bc52333678",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":329,
                  "y":554},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16732070a97b47348c325fd835962429",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":395,
              "y":545},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3dca0decca8a4b0082b99648152fa36c",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":299,
              "y":737},
            "size":{
              "width":313,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91435b732dd94be4b0c4f61cea137ff9",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":313,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0f1866cb7a20436a9dc4e2042da90539",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8df424c93864efd999f3f16178dcac2",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 主页",
                              "target":{
                                "targetType":"page",
                                "url":"主页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}},
{
                  "id":"262fee11b06141349252bdb59c0c393a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":78,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f59b76f34d44e8aa29f8c65f4625e09",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":78,
                          "y":0},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 档案列表",
                              "target":{
                                "targetType":"page",
                                "url":"档案列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}},
{
                  "id":"55b9b7dd3c32440c925cc86b3e4076ce",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":234,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f776909234c5471ebfa30f42d25de7f9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":234,
                          "y":0},
                        "size":{
                          "width":79,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u10.png"}},
{
                  "id":"062a0db7235b425394f981c7e128926a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":156,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cee71de3dcfb48319cfadf6ac85c6373",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":156,
                          "y":0},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻页面",
                              "target":{
                                "targetType":"page",
                                "url":"新闻页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "a51d40b3e0c14b66b84493e173887085":{
      "scriptId":"u0"},
    "cbd31caf67f04a16bc4a598ca3c01ef6":{
      "scriptId":"u1"},
    "276d522fac284b03a2f4719cf6b08be8":{
      "scriptId":"u2"},
    "08d7e84e74144ecd9e9989d4bae5763a":{
      "scriptId":"u3"},
    "c0ddd0e224ba476ba645f91598bbf739":{
      "scriptId":"u4"},
    "7899fcf0b50641eca6574f49c8d46232":{
      "scriptId":"u5"},
    "17e0d1eaaa8a49a1b1024b6dedf3a162":{
      "scriptId":"u6"},
    "263f645751964dd085ca48bb6064f700":{
      "scriptId":"u7"},
    "d208d3b62fc44835941a51cd306705aa":{
      "scriptId":"u8"},
    "9d98559435b24b32b0d294c15c1575a2":{
      "scriptId":"u9"},
    "6eaf96a41e7d4e2b958bc41001a783c7":{
      "scriptId":"u10"},
    "c05e1a766e0c49f7ad1c0e0fe0a3fb91":{
      "scriptId":"u11"},
    "fb266b05adc84507aa585b63e002f2a6":{
      "scriptId":"u12"},
    "56dae8b43d934593aef2e8efb59e3e3f":{
      "scriptId":"u13"},
    "9a28271f901b49dbbd5420c9c6d76b11":{
      "scriptId":"u14"},
    "efc1e169de384f0f93eacaaf27d2a9db":{
      "scriptId":"u15"},
    "2ae8a4dc5cae47e1a855f15843d8d345":{
      "scriptId":"u16"},
    "12421999c394477a95b6b95355baa39f":{
      "scriptId":"u17"},
    "8ed702da76e0437793c8f5865a455f44":{
      "scriptId":"u18"},
    "08d2d5378dd9428b8d7871b1376cb9d8":{
      "scriptId":"u19"},
    "ec4e9bf25a364eb6b785e533f43e53de":{
      "scriptId":"u20"},
    "523a067fa7254b76b017ba0644c2e7d1":{
      "scriptId":"u21"},
    "187b62b8f5944dedbbc92630866610a3":{
      "scriptId":"u22"},
    "35aca19ec5764ce9a279ba12b078b346":{
      "scriptId":"u23"},
    "1a46ebb3d74544f2b595c7476e721e4b":{
      "scriptId":"u24"},
    "32fc2d7eeda248dc8613c5fba885053a":{
      "scriptId":"u25"},
    "af3ab596bcfb4aa2887ffc63b7255ce5":{
      "scriptId":"u26"},
    "d82d32118a7b40a0b2fb090760140668":{
      "scriptId":"u27"},
    "bc0f8cba707f40cfa85b771af6e680da":{
      "scriptId":"u28"},
    "073fffc698c048e9be11852e0f612236":{
      "scriptId":"u29"},
    "536e66b28bd74cbfa73c3d5cbf5371c5":{
      "scriptId":"u30"},
    "2c4cfb46de564f01b00c55360a9e5875":{
      "scriptId":"u31"},
    "6559d4ea74164ee5bd28ec86114742eb":{
      "scriptId":"u32"},
    "730e900946bb41d28fe0ee92e2c658bd":{
      "scriptId":"u33"},
    "198817a2fb7540a1bdbf797164051e26":{
      "scriptId":"u34"},
    "4fd8752a18cb4429965d654ce686a3d8":{
      "scriptId":"u35"},
    "b64a8d1261dc49b9998757e4cfcb40ed":{
      "scriptId":"u36"},
    "013f6fbb2dcd45cbad51ef9f3ebdae98":{
      "scriptId":"u37"},
    "2c09d6a5a5fa49038d53bd1913b0f725":{
      "scriptId":"u38"},
    "47756d43436c413ca39f44e11158dd66":{
      "scriptId":"u39"},
    "7cccf88834044edeb670a8bc52333678":{
      "scriptId":"u40"},
    "16732070a97b47348c325fd835962429":{
      "scriptId":"u41"},
    "3dca0decca8a4b0082b99648152fa36c":{
      "scriptId":"u42"},
    "91435b732dd94be4b0c4f61cea137ff9":{
      "scriptId":"u43"},
    "0f1866cb7a20436a9dc4e2042da90539":{
      "scriptId":"u44"},
    "a8df424c93864efd999f3f16178dcac2":{
      "scriptId":"u45"},
    "262fee11b06141349252bdb59c0c393a":{
      "scriptId":"u46"},
    "0f59b76f34d44e8aa29f8c65f4625e09":{
      "scriptId":"u47"},
    "062a0db7235b425394f981c7e128926a":{
      "scriptId":"u48"},
    "cee71de3dcfb48319cfadf6ac85c6373":{
      "scriptId":"u49"},
    "55b9b7dd3c32440c925cc86b3e4076ce":{
      "scriptId":"u50"},
    "f776909234c5471ebfa30f42d25de7f9":{
      "scriptId":"u51"}}});