$axure.loadCurrentPage({
  "url":"目录档案详情.html",
  "generationDate":new Date(1431048593375),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"num"],
  "page":{
    "packageId":"0873f064ada948e6a79305ca4a1499e8",
    "type":"Axure:Page",
    "name":"目录档案详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7659c2d9fb5e46e790fc4b300f4fef67",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":260,
              "y":80},
            "size":{
              "width":390,
              "height":803}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e66fd1cb7bac432790fe11e51307a16a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":260,
                  "y":80},
                "size":{
                  "width":390,
                  "height":803}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u0.png"}},
{
          "id":"e1827b2321fb4d38ab736a5959d9abf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":300,
              "y":200},
            "size":{
              "width":313,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"381abba192ed46619e9d727a18e0ddb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":200},
                "size":{
                  "width":313,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u17.png"}},
{
          "id":"6c8af19161b94b4b92dea4ebf774e28f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":308,
              "y":211},
            "size":{
              "width":4,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"820775e9f1334c1b8357c4aeb01b8968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":308,
                  "y":211},
                "size":{
                  "width":4,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u19.png"}},
{
          "id":"30bfa55147034df1898b4d37c0ed18c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":314,
              "y":208},
            "size":{
              "width":4,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e02463226be04d808e4d959734671d39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":314,
                  "y":208},
                "size":{
                  "width":4,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u21.png"}},
{
          "id":"ef7132d9b06f45e49ef5ca2e9ef0f898",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":311,
              "y":210},
            "size":{
              "width":4,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6994bd0410b341d6bd6f8db25351b9ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":311,
                  "y":210},
                "size":{
                  "width":4,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u23.png"}},
{
          "id":"b9a4c6cca70340d09dad490a77897af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":321,
              "y":204},
            "size":{
              "width":4,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6a74408667043b294d2335a6ef61908",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":321,
                  "y":204},
                "size":{
                  "width":4,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u25.png"}},
{
          "id":"c3b40ee9339a4a069c3049cd760200f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":586,
              "y":204},
            "size":{
              "width":21,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b71d829eb7cd465791896c7f07fca19d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":586,
                  "y":204},
                "size":{
                  "width":21,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u27.png"}},
{
          "id":"28271b6418e54a3891938ba32806b3e6",
          "label":"iPhoneTime",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":433,
              "y":200},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b222ecd899db4a449229d58862449010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":433,
                  "y":200},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6f8091a99064312a8dcff16a469c76c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"13px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":300,
              "y":220},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"245510c41df54a79aec09550cf2d8b8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"13px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":300,
                  "y":220},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u31.png"}},
{
          "id":"d43bb31fb3e14a61a89c3372a3bb55c4",
          "label":"BUTTON_BACK",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":304,
              "y":223},
            "size":{
              "width":29,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba787bdabf244ce5990aea54fd586bb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":304,
                  "y":223},
                "size":{
                  "width":29,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案列表",
                      "target":{
                        "targetType":"page",
                        "url":"档案列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7980099c01bd4afcbda1072aa701d2b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":416.5,
              "y":682},
            "size":{
              "width":80,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6275de399a412498eb76b2dd98fca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":416.5,
                  "y":682},
                "size":{
                  "width":80,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案详情/u22.png"}},
{
          "id":"d82c85e8b0e7439cac14f4ba7ae714e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":308,
              "y":262},
            "size":{
              "width":262,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9b0dc98341a4b448051b22b2ea0b0cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":308,
                  "y":262},
                "size":{
                  "width":262,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d034bb6bcc7d4340821f3e6385b309dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":300,
              "y":310},
            "size":{
              "width":313,
              "height":362}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eba392935a614175a03f3aeae2708b37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":300,
                  "y":310},
                "size":{
                  "width":313,
                  "height":362}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/目录档案详情/u24.gif"}},
{
          "id":"6217d42270f447c2875cb3fdd7f16f2d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":533,
              "y":224},
            "size":{
              "width":77,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"06c19dbbf26543efad1d24a9ce13d026",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":483,
              "y":249},
            "size":{
              "width":130,
              "height":312}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15cca00b87a49ed8f2163f57e66293f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":483,
                  "y":249},
                "size":{
                  "width":130,
                  "height":312}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/目录档案详情/u27.png"}},
{
          "id":"fd0cf4a0c2764ea78c0800aa03bdf668",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":160,
              "y":360}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e980cf2b949b410496fbc3ac2fbca28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":160,
                  "y":360}},
              "adaptiveStyles":{
}}]},
{
          "id":"044d09674cec4acf8198b117e60d0820",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":322},
            "size":{
              "width":200,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc4cdd183d804f89b8a4e694ac23fde2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":322},
                "size":{
                  "width":200,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7659c2d9fb5e46e790fc4b300f4fef67":{
      "scriptId":"u0"},
    "e66fd1cb7bac432790fe11e51307a16a":{
      "scriptId":"u1"},
    "e1827b2321fb4d38ab736a5959d9abf9":{
      "scriptId":"u2"},
    "381abba192ed46619e9d727a18e0ddb8":{
      "scriptId":"u3"},
    "6c8af19161b94b4b92dea4ebf774e28f":{
      "scriptId":"u4"},
    "820775e9f1334c1b8357c4aeb01b8968":{
      "scriptId":"u5"},
    "30bfa55147034df1898b4d37c0ed18c0":{
      "scriptId":"u6"},
    "e02463226be04d808e4d959734671d39":{
      "scriptId":"u7"},
    "ef7132d9b06f45e49ef5ca2e9ef0f898":{
      "scriptId":"u8"},
    "6994bd0410b341d6bd6f8db25351b9ae":{
      "scriptId":"u9"},
    "b9a4c6cca70340d09dad490a77897af3":{
      "scriptId":"u10"},
    "a6a74408667043b294d2335a6ef61908":{
      "scriptId":"u11"},
    "c3b40ee9339a4a069c3049cd760200f7":{
      "scriptId":"u12"},
    "b71d829eb7cd465791896c7f07fca19d":{
      "scriptId":"u13"},
    "28271b6418e54a3891938ba32806b3e6":{
      "scriptId":"u14"},
    "b222ecd899db4a449229d58862449010":{
      "scriptId":"u15"},
    "d6f8091a99064312a8dcff16a469c76c":{
      "scriptId":"u16"},
    "245510c41df54a79aec09550cf2d8b8a":{
      "scriptId":"u17"},
    "d43bb31fb3e14a61a89c3372a3bb55c4":{
      "scriptId":"u18"},
    "ba787bdabf244ce5990aea54fd586bb1":{
      "scriptId":"u19"},
    "7980099c01bd4afcbda1072aa701d2b5":{
      "scriptId":"u20"},
    "8d6275de399a412498eb76b2dd98fca0":{
      "scriptId":"u21"},
    "d82c85e8b0e7439cac14f4ba7ae714e7":{
      "scriptId":"u22"},
    "d9b0dc98341a4b448051b22b2ea0b0cc":{
      "scriptId":"u23"},
    "d034bb6bcc7d4340821f3e6385b309dc":{
      "scriptId":"u24"},
    "eba392935a614175a03f3aeae2708b37":{
      "scriptId":"u25"},
    "6217d42270f447c2875cb3fdd7f16f2d":{
      "scriptId":"u26"},
    "06c19dbbf26543efad1d24a9ce13d026":{
      "scriptId":"u27"},
    "b15cca00b87a49ed8f2163f57e66293f":{
      "scriptId":"u28"},
    "fd0cf4a0c2764ea78c0800aa03bdf668":{
      "scriptId":"u29"},
    "e980cf2b949b410496fbc3ac2fbca28b":{
      "scriptId":"u30"},
    "044d09674cec4acf8198b117e60d0820":{
      "scriptId":"u31"},
    "bc4cdd183d804f89b8a4e694ac23fde2":{
      "scriptId":"u32"}}});