$axure.loadCurrentPage({
  "url":"档案列表.html",
  "generationDate":new Date(1431048592906.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"num"],
  "page":{
    "packageId":"d7af5d1d752449518590792722f69398",
    "type":"Axure:Page",
    "name":"档案列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4a094c9b047a4033b74397c66c10e268",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":261,
              "y":80},
            "size":{
              "width":389,
              "height":803}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d561b33c99d44ec87ef950664bdd2a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":261,
                  "y":80},
                "size":{
                  "width":389,
                  "height":803}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u0.png"}},
{
          "id":"c3cbe33d2d8e45049601765009dd5b9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"13px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009999},
            "location":{
              "x":300,
              "y":220},
            "size":{
              "width":313,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe564c266bf4b41a7eabc8bdb353a05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"13px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009999},
                "location":{
                  "x":300,
                  "y":220},
                "size":{
                  "width":313,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u31.png"}},
{
          "id":"cf56ac62866f4720ab9d9082b02100ce",
          "label":"border",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":360,
              "y":223},
            "size":{
              "width":212,
              "height":27},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009DDA},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27cab4e47747461a90907457272bc8b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":360,
                  "y":223},
                "size":{
                  "width":212,
                  "height":27},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009DDA},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/border_u4.png"}},
{
          "id":"6b22689538784650ab272d05732067af",
          "label":"sou",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "stateStyles":{
              "hint":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":366,
              "y":226},
            "size":{
              "width":176,
              "height":22}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入关键字搜索"},
{
          "id":"2083718e0a5d4c3d835117e4c9f9f868",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "baseStyle":"627587b6038d43cca051c114ac41ad32",
            "location":{
              "x":586,
              "y":225},
            "size":{
              "width":20,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6fdc01af674414a2e6dba6e27dfe17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                "location":{
                  "x":586,
                  "y":225},
                "size":{
                  "width":20,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u7.png"}},
{
          "id":"4e70248e520b42b6b90a0111fa652afc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":301,
              "y":201},
            "size":{
              "width":313,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdcd9cedd2e24c009af6d81b9754ec2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":301,
                  "y":201},
                "size":{
                  "width":313,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u17.png"}},
{
          "id":"505476469dbc4fe9bd8063732666913b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":309,
              "y":212},
            "size":{
              "width":4,
              "height":5},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f10518483ef4893956702bb0c2d8e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":309,
                  "y":212},
                "size":{
                  "width":4,
                  "height":5},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u19.png"}},
{
          "id":"f71dba1845634b70a3afee69fda91445",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":315,
              "y":209},
            "size":{
              "width":4,
              "height":8},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e812caebccc42d19738eeed9f2313a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":315,
                  "y":209},
                "size":{
                  "width":4,
                  "height":8},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u21.png"}},
{
          "id":"dab0317b290147f7a4c29b6ceedadd09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":312,
              "y":211},
            "size":{
              "width":4,
              "height":6},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95950c7817d740beba62146386214b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":312,
                  "y":211},
                "size":{
                  "width":4,
                  "height":6},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u23.png"}},
{
          "id":"27ce7c7d2c824377a8f7826310d43232",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF868686},
            "location":{
              "x":322,
              "y":205},
            "size":{
              "width":4,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f445e78c165f4e86a68c0a2ebbdb0705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF868686},
                "location":{
                  "x":322,
                  "y":205},
                "size":{
                  "width":4,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u25.png"}},
{
          "id":"f2735f9c4a5648299a00f5fc52b0df90",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFA1A1A1},
            "location":{
              "x":587,
              "y":205},
            "size":{
              "width":21,
              "height":12},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c7cef33f654afa9f7c9402ffb3a7f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1},
                "location":{
                  "x":587,
                  "y":205},
                "size":{
                  "width":21,
                  "height":12},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/云档案app/u27.png"}},
{
          "id":"75c1b91eb4c64b3d9f7db341dd8275f6",
          "label":"iPhoneTime",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"8px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":434,
              "y":201},
            "size":{
              "width":40,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3713df7167f34b60a79169a9148c0dc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"8px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":434,
                  "y":201},
                "size":{
                  "width":40,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50facda50b4c4109bc46034580af3b78",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":300,
              "y":262},
            "size":{
              "width":308,
              "height":462},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa9035d8faad47c5bf54fa5e7b0553a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":300,
                  "y":262},
                "size":{
                  "width":308,
                  "height":462},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u23.png"}},
{
          "id":"c30043fa852a4d4e851d6c1e6d5dcb97",
          "label":"BUTTON_BACK",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":304,
              "y":223},
            "size":{
              "width":29,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"6"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d25691f105f4456a93059068b128f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":304,
                  "y":223},
                "size":{
                  "width":29,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"6"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ad1d881e5c6440a9080622c565cba97",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":359},
            "size":{
              "width":291,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/档案列表/u27_line.png"}},
{
          "id":"84d3a408114f4c5392e49978d755fb16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":309,
              "y":270},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a598ab62b4e04568b9154f555ebb3286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":309,
                  "y":270},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u28.png"}},
{
          "id":"1bc46c7c93554e689af23756be9dcd63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":315,
              "y":277},
            "size":{
              "width":104,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675fb5c38da545488c6f1927c4137cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":315,
                  "y":277},
                "size":{
                  "width":104,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案列表/u30.png"}},
{
          "id":"32b15ef675474d9291ab1bcb61162921",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":443,
              "y":272},
            "size":{
              "width":155,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636dab4aa8a64e4da3fdc187d7344799",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":443,
                  "y":272},
                "size":{
                  "width":155,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u32.png"}},
{
          "id":"8ce8004568174f2f98ffc9d737f8db82",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":444,
              "y":300},
            "size":{
              "width":67,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d4f67b38650445e96c7b1828bd13b57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":444,
                  "y":300},
                "size":{
                  "width":67,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u34.png"}},
{
          "id":"4589e7cef01347d8b4d59b6113785c29",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":458},
            "size":{
              "width":291,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/档案列表/u27_line.png"}},
{
          "id":"77c35d476ce34e0c83877a77359fe043",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":309,
              "y":369},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23372e4f4fb1409c8d63ca7576a28989",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":309,
                  "y":369},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u37.png"}},
{
          "id":"f4a617626ba24801af8a2dea4b187c7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":315,
              "y":376},
            "size":{
              "width":104,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3249bb87ed454163a7425cfcf852b2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":315,
                  "y":376},
                "size":{
                  "width":104,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案列表/u39.png"}},
{
          "id":"4d10e91fed7b46a18c31e845f031a678",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":447,
              "y":429},
            "size":{
              "width":81,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528ac518abf54457ab813f0759707251",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":447,
                  "y":429},
                "size":{
                  "width":81,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u41.png"}},
{
          "id":"d0ca9b0c423d44ec8a13e53ac0ef5d40",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":309,
              "y":468},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e10059c026476aab9cb092cbc22a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":309,
                  "y":468},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u28.png"}},
{
          "id":"6756dadb8f2d41f2b3f828ca14a472c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":315,
              "y":475},
            "size":{
              "width":104,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9888e8a4d9614a3a956f3a69878ac2f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":315,
                  "y":475},
                "size":{
                  "width":104,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案列表/u30.png"}},
{
          "id":"d1b976d4e2084b199ad2af96f4bc103c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":557},
            "size":{
              "width":291,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/档案列表/u27_line.png"}},
{
          "id":"46921b0538bd4468b6ebacfe827afcd0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":308,
              "y":567},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87ca217a67124262bcdb3c82f58eb7ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":308,
                  "y":567},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u48.png"}},
{
          "id":"bea9ac253fa74b3898968e9b22e4c974",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":314,
              "y":574},
            "size":{
              "width":104,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"073694b6c5c745ddba335b6baa78c1a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":314,
                  "y":574},
                "size":{
                  "width":104,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案列表/u50.png"}},
{
          "id":"ef652eb3d5cb47bb9ca01bdb17e7d4ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":308,
              "y":657},
            "size":{
              "width":297,
              "height":89},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec7971d3f8d407b86473481a7098c3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":308,
                  "y":657},
                "size":{
                  "width":297,
                  "height":89},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u28.png"}},
{
          "id":"5013b60ff3f34554b1f914dfbda7fe47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":314,
              "y":664},
            "size":{
              "width":104,
              "height":69},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d2109cf2ba249ab92406150301b4599",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":314,
                  "y":664},
                "size":{
                  "width":104,
                  "height":69},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/档案列表/u30.png"}},
{
          "id":"bb486f64c71049a99db071e5ae6413bb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":760,
              "y":300}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828d5e98008f4cd28a89e14ab744b28b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":760,
                  "y":300}},
              "adaptiveStyles":{
}}]},
{
          "id":"c862a953b8df4abb8aacb63da8681b59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":670,
              "y":323},
            "size":{
              "width":114,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57f551a02fcd44be91a9b3239b268512",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":670,
                  "y":323},
                "size":{
                  "width":114,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65e6b1d3e6004fd6a22f68fbf5fa73b8",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":800,
              "y":570}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"080bb6d25b3044eb885f9a53926596d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":800,
                  "y":570}},
              "adaptiveStyles":{
}}]},
{
          "id":"c7629aeb9a6f4853b118f34fd34d52f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":670,
              "y":537},
            "size":{
              "width":114,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dff6b98107e442b8887d16411e3c519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":670,
                  "y":537},
                "size":{
                  "width":114,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"652eeb21b16947658a64c47fbe9a97b0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":794,
              "y":202}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"092433e17ee1469c869ee1f4ce21ba24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":794,
                  "y":202}},
              "adaptiveStyles":{
}}]},
{
          "id":"a4a156293e2747399006fb09742182eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":660,
              "y":220},
            "size":{
              "width":114,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48d3dc15863140aa8261e1231afc04db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":660,
                  "y":220},
                "size":{
                  "width":114,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"527662cd9ac94a9da60a1dcccbf579ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9966},
            "location":{
              "x":670,
              "y":687},
            "size":{
              "width":114,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99db1096e6ee42fd8e8b18af4b39e815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9966},
                "location":{
                  "x":670,
                  "y":687},
                "size":{
                  "width":114,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u68.png"}},
{
          "id":"9656df10dabf48c2a41ed653c96e4c30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":542,
              "y":223},
            "size":{
              "width":28,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b3eb9fb8cac4362885c754c431ba501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":542,
                  "y":223},
                "size":{
                  "width":28,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u75.ico"}},
{
          "id":"96a21f27f1a64cb293e012683781e4e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":443,
              "y":335},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93bad1075244440986ad9dfb081fd8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":443,
                  "y":335},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案详情",
                      "target":{
                        "targetType":"page",
                        "url":"档案详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"222b380985f847878e347c484204c69d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":447,
              "y":531},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa9119d34974cdd9d52115fcfd7f293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":447,
                  "y":531},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案详情",
                      "target":{
                        "targetType":"page",
                        "url":"档案详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"791796bb95364d658ef42f939edbe496",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":447,
              "y":631},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a127a45d4e1b49e4b84f83963a579c1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":447,
                  "y":631},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 档案详情",
                      "target":{
                        "targetType":"page",
                        "url":"档案详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c047fc8454cd4094b81d97cb60571a2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":441,
              "y":717},
            "size":{
              "width":140,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3842c0207ef34630b738c82b518009b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":441,
                  "y":717},
                "size":{
                  "width":140,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 目录档案详情",
                      "target":{
                        "targetType":"page",
                        "url":"目录档案详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"351fdf7506d347af89c5781e5f24d885",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":443,
              "y":379},
            "size":{
              "width":155,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1af2301a369c401694fa3b2863d65a6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":443,
                  "y":379},
                "size":{
                  "width":155,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u32.png"}},
{
          "id":"895be6f0cc37483ba4a15e888c84aae2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":444,
              "y":407},
            "size":{
              "width":67,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3ee2c8011b04034b1360edaea8b7d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":444,
                  "y":407},
                "size":{
                  "width":67,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u34.png"}},
{
          "id":"84390bc8b30742489839862c8a50aff6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":444,
              "y":477},
            "size":{
              "width":155,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61166294b9ae4a0ea1fece80e9596d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":444,
                  "y":477},
                "size":{
                  "width":155,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u32.png"}},
{
          "id":"23b7769647b74f70b6247024ca001fee",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":445,
              "y":505},
            "size":{
              "width":67,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11959c71c5044dd6b32d86337bcb63ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":445,
                  "y":505},
                "size":{
                  "width":67,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u34.png"}},
{
          "id":"ae5dedde0dfb48e39a5a8366ee8a1999",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":447,
              "y":577},
            "size":{
              "width":155,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704e5ed211094bec818b3f905b490f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":447,
                  "y":577},
                "size":{
                  "width":155,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u32.png"}},
{
          "id":"9980daa336504634be1c1a0ce919aee8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":448,
              "y":605},
            "size":{
              "width":67,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae2e39ce583d4b0a9ef02152c3bfd55e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":448,
                  "y":605},
                "size":{
                  "width":67,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u34.png"}},
{
          "id":"568d652518784c8f9ec25a66e3a887fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":447,
              "y":666},
            "size":{
              "width":155,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e193eb487f466c98070771899c0f61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":447,
                  "y":666},
                "size":{
                  "width":155,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u32.png"}},
{
          "id":"1fa7da19a62b4e1da9cab700e3be1dd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFFF},
            "location":{
              "x":448,
              "y":694},
            "size":{
              "width":67,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF363636}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7498940ff254a6fa2ba4504e89f3f00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF},
                "location":{
                  "x":448,
                  "y":694},
                "size":{
                  "width":67,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF363636}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/档案列表/u34.png"}},
{
          "id":"0e2d342b915e46449764d12fab31869f",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":737},
            "size":{
              "width":313,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7992dfd852f44afea486e0796a370948",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":313,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23188984264941a1855ea7e35b76c128",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"431056c1fafc4117a1a324e89ee31bb0",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 主页",
                              "target":{
                                "targetType":"page",
                                "url":"主页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}},
{
                  "id":"c43e3eae76364a438bda3035ff269603",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":78,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"742e756bae81421f9bd0029efec5c881",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":78,
                          "y":0},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 档案列表",
                              "target":{
                                "targetType":"page",
                                "url":"档案列表.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}},
{
                  "id":"0db4f188a2e440bf8a60a73d5066642c",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":234,
                      "y":0},
                    "size":{
                      "width":79,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"106827ac4a5041e19dc4b1cbce95e293",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":234,
                          "y":0},
                        "size":{
                          "width":79,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u10.png"}},
{
                  "id":"97c5a472ef7f4bf1be7f72990ded0428",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":156,
                      "y":0},
                    "size":{
                      "width":78,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99603ffbad1840e082701772d18d4f9b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":156,
                          "y":0},
                        "size":{
                          "width":78,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 新闻页面",
                              "target":{
                                "targetType":"page",
                                "url":"新闻页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/主页/u4.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "4a094c9b047a4033b74397c66c10e268":{
      "scriptId":"u0"},
    "5d561b33c99d44ec87ef950664bdd2a4":{
      "scriptId":"u1"},
    "c3cbe33d2d8e45049601765009dd5b9e":{
      "scriptId":"u2"},
    "2fe564c266bf4b41a7eabc8bdb353a05":{
      "scriptId":"u3"},
    "cf56ac62866f4720ab9d9082b02100ce":{
      "scriptId":"u4"},
    "27cab4e47747461a90907457272bc8b2":{
      "scriptId":"u5"},
    "6b22689538784650ab272d05732067af":{
      "scriptId":"u6"},
    "2083718e0a5d4c3d835117e4c9f9f868":{
      "scriptId":"u7"},
    "0f6fdc01af674414a2e6dba6e27dfe17":{
      "scriptId":"u8"},
    "4e70248e520b42b6b90a0111fa652afc":{
      "scriptId":"u9"},
    "bdcd9cedd2e24c009af6d81b9754ec2f":{
      "scriptId":"u10"},
    "505476469dbc4fe9bd8063732666913b":{
      "scriptId":"u11"},
    "0f10518483ef4893956702bb0c2d8e3d":{
      "scriptId":"u12"},
    "f71dba1845634b70a3afee69fda91445":{
      "scriptId":"u13"},
    "0e812caebccc42d19738eeed9f2313a3":{
      "scriptId":"u14"},
    "dab0317b290147f7a4c29b6ceedadd09":{
      "scriptId":"u15"},
    "95950c7817d740beba62146386214b46":{
      "scriptId":"u16"},
    "27ce7c7d2c824377a8f7826310d43232":{
      "scriptId":"u17"},
    "f445e78c165f4e86a68c0a2ebbdb0705":{
      "scriptId":"u18"},
    "f2735f9c4a5648299a00f5fc52b0df90":{
      "scriptId":"u19"},
    "54c7cef33f654afa9f7c9402ffb3a7f2":{
      "scriptId":"u20"},
    "75c1b91eb4c64b3d9f7db341dd8275f6":{
      "scriptId":"u21"},
    "3713df7167f34b60a79169a9148c0dc5":{
      "scriptId":"u22"},
    "50facda50b4c4109bc46034580af3b78":{
      "scriptId":"u23"},
    "fa9035d8faad47c5bf54fa5e7b0553a0":{
      "scriptId":"u24"},
    "c30043fa852a4d4e851d6c1e6d5dcb97":{
      "scriptId":"u25"},
    "3d25691f105f4456a93059068b128f8c":{
      "scriptId":"u26"},
    "9ad1d881e5c6440a9080622c565cba97":{
      "scriptId":"u27"},
    "84d3a408114f4c5392e49978d755fb16":{
      "scriptId":"u28"},
    "a598ab62b4e04568b9154f555ebb3286":{
      "scriptId":"u29"},
    "1bc46c7c93554e689af23756be9dcd63":{
      "scriptId":"u30"},
    "675fb5c38da545488c6f1927c4137cc6":{
      "scriptId":"u31"},
    "32b15ef675474d9291ab1bcb61162921":{
      "scriptId":"u32"},
    "636dab4aa8a64e4da3fdc187d7344799":{
      "scriptId":"u33"},
    "8ce8004568174f2f98ffc9d737f8db82":{
      "scriptId":"u34"},
    "2d4f67b38650445e96c7b1828bd13b57":{
      "scriptId":"u35"},
    "4589e7cef01347d8b4d59b6113785c29":{
      "scriptId":"u36"},
    "77c35d476ce34e0c83877a77359fe043":{
      "scriptId":"u37"},
    "23372e4f4fb1409c8d63ca7576a28989":{
      "scriptId":"u38"},
    "f4a617626ba24801af8a2dea4b187c7f":{
      "scriptId":"u39"},
    "3249bb87ed454163a7425cfcf852b2d1":{
      "scriptId":"u40"},
    "4d10e91fed7b46a18c31e845f031a678":{
      "scriptId":"u41"},
    "528ac518abf54457ab813f0759707251":{
      "scriptId":"u42"},
    "d0ca9b0c423d44ec8a13e53ac0ef5d40":{
      "scriptId":"u43"},
    "07e10059c026476aab9cb092cbc22a31":{
      "scriptId":"u44"},
    "6756dadb8f2d41f2b3f828ca14a472c0":{
      "scriptId":"u45"},
    "9888e8a4d9614a3a956f3a69878ac2f2":{
      "scriptId":"u46"},
    "d1b976d4e2084b199ad2af96f4bc103c":{
      "scriptId":"u47"},
    "46921b0538bd4468b6ebacfe827afcd0":{
      "scriptId":"u48"},
    "87ca217a67124262bcdb3c82f58eb7ce":{
      "scriptId":"u49"},
    "bea9ac253fa74b3898968e9b22e4c974":{
      "scriptId":"u50"},
    "073694b6c5c745ddba335b6baa78c1a6":{
      "scriptId":"u51"},
    "ef652eb3d5cb47bb9ca01bdb17e7d4ab":{
      "scriptId":"u52"},
    "2ec7971d3f8d407b86473481a7098c3c":{
      "scriptId":"u53"},
    "5013b60ff3f34554b1f914dfbda7fe47":{
      "scriptId":"u54"},
    "2d2109cf2ba249ab92406150301b4599":{
      "scriptId":"u55"},
    "bb486f64c71049a99db071e5ae6413bb":{
      "scriptId":"u56"},
    "828d5e98008f4cd28a89e14ab744b28b":{
      "scriptId":"u57"},
    "c862a953b8df4abb8aacb63da8681b59":{
      "scriptId":"u58"},
    "57f551a02fcd44be91a9b3239b268512":{
      "scriptId":"u59"},
    "65e6b1d3e6004fd6a22f68fbf5fa73b8":{
      "scriptId":"u60"},
    "080bb6d25b3044eb885f9a53926596d5":{
      "scriptId":"u61"},
    "c7629aeb9a6f4853b118f34fd34d52f5":{
      "scriptId":"u62"},
    "0dff6b98107e442b8887d16411e3c519":{
      "scriptId":"u63"},
    "652eeb21b16947658a64c47fbe9a97b0":{
      "scriptId":"u64"},
    "092433e17ee1469c869ee1f4ce21ba24":{
      "scriptId":"u65"},
    "a4a156293e2747399006fb09742182eb":{
      "scriptId":"u66"},
    "48d3dc15863140aa8261e1231afc04db":{
      "scriptId":"u67"},
    "527662cd9ac94a9da60a1dcccbf579ea":{
      "scriptId":"u68"},
    "99db1096e6ee42fd8e8b18af4b39e815":{
      "scriptId":"u69"},
    "9656df10dabf48c2a41ed653c96e4c30":{
      "scriptId":"u70"},
    "8b3eb9fb8cac4362885c754c431ba501":{
      "scriptId":"u71"},
    "96a21f27f1a64cb293e012683781e4e9":{
      "scriptId":"u72"},
    "d93bad1075244440986ad9dfb081fd8c":{
      "scriptId":"u73"},
    "222b380985f847878e347c484204c69d":{
      "scriptId":"u74"},
    "7aa9119d34974cdd9d52115fcfd7f293":{
      "scriptId":"u75"},
    "791796bb95364d658ef42f939edbe496":{
      "scriptId":"u76"},
    "a127a45d4e1b49e4b84f83963a579c1a":{
      "scriptId":"u77"},
    "c047fc8454cd4094b81d97cb60571a2e":{
      "scriptId":"u78"},
    "3842c0207ef34630b738c82b518009b7":{
      "scriptId":"u79"},
    "351fdf7506d347af89c5781e5f24d885":{
      "scriptId":"u80"},
    "1af2301a369c401694fa3b2863d65a6f":{
      "scriptId":"u81"},
    "895be6f0cc37483ba4a15e888c84aae2":{
      "scriptId":"u82"},
    "e3ee2c8011b04034b1360edaea8b7d1d":{
      "scriptId":"u83"},
    "84390bc8b30742489839862c8a50aff6":{
      "scriptId":"u84"},
    "61166294b9ae4a0ea1fece80e9596d5b":{
      "scriptId":"u85"},
    "23b7769647b74f70b6247024ca001fee":{
      "scriptId":"u86"},
    "11959c71c5044dd6b32d86337bcb63ee":{
      "scriptId":"u87"},
    "ae5dedde0dfb48e39a5a8366ee8a1999":{
      "scriptId":"u88"},
    "704e5ed211094bec818b3f905b490f8c":{
      "scriptId":"u89"},
    "9980daa336504634be1c1a0ce919aee8":{
      "scriptId":"u90"},
    "ae2e39ce583d4b0a9ef02152c3bfd55e":{
      "scriptId":"u91"},
    "568d652518784c8f9ec25a66e3a887fa":{
      "scriptId":"u92"},
    "71e193eb487f466c98070771899c0f61":{
      "scriptId":"u93"},
    "1fa7da19a62b4e1da9cab700e3be1dd7":{
      "scriptId":"u94"},
    "d7498940ff254a6fa2ba4504e89f3f00":{
      "scriptId":"u95"},
    "0e2d342b915e46449764d12fab31869f":{
      "scriptId":"u96"},
    "7992dfd852f44afea486e0796a370948":{
      "scriptId":"u97"},
    "23188984264941a1855ea7e35b76c128":{
      "scriptId":"u98"},
    "431056c1fafc4117a1a324e89ee31bb0":{
      "scriptId":"u99"},
    "c43e3eae76364a438bda3035ff269603":{
      "scriptId":"u100"},
    "742e756bae81421f9bd0029efec5c881":{
      "scriptId":"u101"},
    "97c5a472ef7f4bf1be7f72990ded0428":{
      "scriptId":"u102"},
    "99603ffbad1840e082701772d18d4f9b":{
      "scriptId":"u103"},
    "0db4f188a2e440bf8a60a73d5066642c":{
      "scriptId":"u104"},
    "106827ac4a5041e19dc4b1cbce95e293":{
      "scriptId":"u105"}}});